### ISSUE TITLE
webhook support

### ISSUE THREAD

**Issue by gajop** [springfiles/springrts_logs#10]
Would it be possible to add some support for webhooks? I'm (slowly..) building the spring-launcher site and I would like to notify developers when an log related to their game is uploaded. Also pretty useful for me as the spring-launcher dev while it's still in its early stages of development. 

PS: I'm not sure how webhooks are usually designed as. Feel free to design the format yourself, although basing it on JSON messages would be appreciated.

**Comment by dansan** [comment]
There is already a RSS feed. But that's not a callback.

This looks promising: https://github.com/zapier/django-rest-hooks

How would the registration work? Would you require one hook for every upload, and filter through the results yourself and notify your users? Or do you want to register one hook per one of your users and have different URLs to connect to?

**Comment by gajop** [comment]
I think having just one hook for everything, and letting me filter would be simplest, at least for now.

**Comment by dansan** [comment]
@gajop Tell me a URL that accept a POST request. For each created logfile object, it will receive:
```
User-Agent: python-requests/2.19.1
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
Content-Type: application/json
Content-Length: 197

{"hook": {"target": "$YOUR_URL", "event": "logfile.added", "id": 1}, "data": {"created": "2019-02-17T18:48:44.918Z", "text": "foo", "id": 14, "tags": ["foo", "foo2"], "name": "bar bar bar"}}
```

**Comment by dansan** [comment]
Oh wait... you only want to be notified for uploads with tag... which one?

**Comment by dansan** [comment]
OK - this will now only trigger on certain tags (like `spring-launcher`).
