### ISSUE TITLE
invalid file encodings in syslog

### ISSUE THREAD

**Issue by abma** [springfiles/springrts_logs#4]
in syslog there are several errors wrt wrong file encoding.

can't provide details atm, sorry

**Comment by dansan** [comment]
I modified the systemd start scripts.
access.log and error.log are now /home/infolog/springrts_logs.access.log and /home/infolog/springrts_logs.error.log.
Nothing should go to syslog.
I'll see if I can find such an error there.

**Comment by abma** [comment]
if i understood the error correctly: uploaded files caused tracebacks with "invalid file encoding".

that the log goes to syslog / journal was/is fine.

**Comment by dansan** [comment]
I cannot reproduce this.
I'll just wait until it happens again.
Or do you still have the traceback?

**Comment by abma** [comment]
sorry, no clue: i can't find it in old logs :-|
